CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(255)                            NOT NULL,

    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_name UNIQUE ("name")
);

CREATE TABLE IF NOT EXISTS categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,

    CONSTRAINT pk_category PRIMARY KEY (id),
    CONSTRAINT uq_category_name UNIQUE ("name")
);

CREATE TABLE IF NOT EXISTS events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    initiator_id       BIGINT                                  NOT NULL,
    category_id        BIGINT                                  NOT NULL,
    title              VARCHAR(100)                            NOT NULL,
    annotation         VARCHAR(2000)                           NOT NULL,
    description        VARCHAR(7000)                           NOT NULL,
    event_date         TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    location_lat       REAL                                    NOT NULL,
    location_lon       REAL                                    NOT NULL,
    paid               BOOLEAN                                 NOT NULL,
    request_moderation BOOLEAN                                 NOT NULL,
    participant_limit  INTEGER                                 NOT NULL,
    state              VARCHAR(64)                             NOT NULL,
    created_on         TIMESTAMP WITHOUT TIME ZONE DEFAULT current_timestamp,
    published_on       TIMESTAMP WITHOUT TIME ZONE,
    confirmed_requests BIGINT                      DEFAULT 0,

    CONSTRAINT pk_event PRIMARY KEY (id),
    CONSTRAINT fk_event_category FOREIGN KEY (category_id) REFERENCES categories (id) ON DELETE CASCADE,
    CONSTRAINT fk_event_initiator FOREIGN KEY (initiator_id) REFERENCES users (id) ON DELETE CASCADE
);
