version: '3.1'
services:
  stats-server:
    container_name: stats-server
    build: ./stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      STATS_DB_URL: jdbc:postgresql://stats-db:5432/stats-db
      STATS_DB_USERNAME: stats-db-user
      STATS_DB_PASSWORD: stats-db-pwd

  stats-db:
    container_name: stats-db
    image: postgres:15.1-alpine
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: stats-db
      POSTGRES_USER: stats-db-user
      POSTGRES_PASSWORD: stats-db-pwd
      TZ: "Europe/Moscow"

  ewm-server:
    container_name: ewm-server
    build: ./ewm-server
    ports:
      - "8080:8080"
    depends_on:
      - stats-server
    environment:
      STATS_SERVER_URL: http://stats-server:9090

#  ewm-db:
#    image: postgres:14-alpine
