version: '3.1'
services:
  stats-server:
    build:
      context: .
      dockerfile: ./stats-server/Dockerfile
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      STATS_DB_URL: jdbc:postgresql://stats-db:5432/stats-db
      STATS_DB_USERNAME: stats-db-user
      STATS_DB_PASSWORD: stats-db-pwd

  stats-db:
    image: postgres:15.1-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: stats-db
      POSTGRES_USER: stats-db-user
      POSTGRES_PASSWORD: stats-db-pwd
      TZ: "Europe/Moscow"

#  ewm-service:
#    ports:
#      - "8080:8080"

#  ewm-db:
#    image: postgres:14-alpine
