version: '3.1'
services:
  stats-service:
    container_name: stats-service
    build: ./stats-service
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      STATS_DB_URL: jdbc:postgresql://stats-db:5432/stats-db
      STATS_DB_USERNAME: stats-db-user
      STATS_DB_PASSWORD: stats-db-pwd

  stats-db:
    container_name: stats-db
    image: postgres:15.1-alpine
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: stats-db
      POSTGRES_USER: stats-db-user
      POSTGRES_PASSWORD: stats-db-pwd
      TZ: "Europe/Moscow"

  ewm-service:
    container_name: ewm-service
    build: ./ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - stats-service
      - ewm-db
    environment:
      STATS_SERVICE_URL: http://stats-service:9090
      EWM_DB_URL: jdbc:postgresql://ewm-db:5432/ewm-db
      EWM_DB_USERNAME: ewm-db-user
      EWM_DB_PASSWORD: ewm-db-pwd

  ewm-db:
    container_name: ewm-db
    image: postgres:15.1-alpine
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB: ewm-db
      POSTGRES_USER: ewm-db-user
      POSTGRES_PASSWORD: ewm-db-pwd
      TZ: "Europe/Moscow"
