CREATE TABLE IF NOT EXISTS apps
(
    id   SMALLINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) UNIQUE                       NOT NULL,

    CONSTRAINT pk_app PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS uris
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    path VARCHAR(255) UNIQUE                     NOT NULL,

    CONSTRAINT pk_uri PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS hits
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app_id  SMALLINT                                NOT NULL,
    uri_id  BIGINT                                  NOT NULL,
    ip      INET                                    NOT NULL,
    created TIMESTAMP WITHOUT TIME ZONE             NOT NULL DEFAULT current_timestamp,

    CONSTRAINT pk_hit PRIMARY KEY (id),
    CONSTRAINT fk_hit_app FOREIGN KEY (app_id) REFERENCES apps (id) ON DELETE CASCADE,
    CONSTRAINT fk_hit_uri FOREIGN KEY (uri_id) REFERENCES uris (id) ON DELETE CASCADE
);
